#!/bin/bash
total 4
-rw-r--r-- 1 root root  0 May 27 08:38 0-current_working_directory
-rwxr-xr-x 1 root root  0 May 27 08:47 1-listit
-rw-r--r-- 1 root root 71 May 27 08:57 2-bring_me_home
-rw-r--r-- 1 root root  0 May 27 08:59 3-listfiles

